# Reshaping

In [1]:
import numpy as np

In [5]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = arr1.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
for i in arr1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [11]:
for i in arr1.ravel():
    print(i)

1
2
3
4
5
6
7
8
9


In [12]:
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
arr2 = np.arange(10,19).reshape(3,3)
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [15]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [16]:
np.hsplit(arr1,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [18]:
np.vsplit(arr1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [19]:
arr3 = np.arange(24).reshape(6,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
arr3[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

# Flitering

In [22]:
arr4 = np.random.randint(low=1, high=100,size=20).reshape(4,5)
arr4

array([[74, 71, 30, 50,  5],
       [55, 91, 88, 22, 29],
       [68, 71, 70, 88, 22],
       [96, 49, 18, 71, 70]], dtype=int32)

In [25]:
arr4>30

array([[ True,  True, False,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [26]:
arr4[arr4>50]

array([74, 71, 55, 91, 88, 68, 71, 70, 88, 96, 71, 70], dtype=int32)

In [27]:
arr4[(arr4>50) & (arr4%2!=0)]

array([71, 55, 91, 71, 71], dtype=int32)

In [28]:
arr4[arr4<30] = 0
arr4

array([[74, 71, 30, 50,  0],
       [55, 91, 88,  0,  0],
       [68, 71, 70, 88,  0],
       [96, 49,  0, 71, 70]], dtype=int32)