# Broadcasting


In [3]:
import numpy as np 

In [5]:
arr1 = np.arange(8).reshape(2,4)
arr2 = np.arange(8,16).reshape(2,4)
print(arr1)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [6]:
arr1+arr2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
arr1+[10]

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [10]:
arr3 = np.arange(9).reshape(3,3)
arr4 = np.arange(3).reshape(1,3)
print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [11]:
arr3+arr4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [17]:
arr4 = arr4.reshape(3,1)
arr4

array([[1],
       [2],
       [3]])

In [18]:
arr3+arr4

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [19]:
arr5 = np.arange(3,6)
print(arr4)

[[1]
 [2]
 [3]]


In [20]:
arr5

array([3, 4, 5])

In [21]:
arr4+arr5

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])