In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [7]:
arr1.shape
#arr2.shape

(9,)

In [8]:
arr2.ndim

2

In [9]:
arr2.size

4

In [10]:
arr2.itemsize

8

In [12]:
arr1.dtype

dtype('int64')

In [17]:
arr3 = arr1.astype('float')
arr3

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
arr3.dtype

dtype('float64')

In [19]:
arr3.itemsize

8

In [20]:
import sys #this library to get size

In [28]:
lista = range(100)
arr = np.array(range(100), dtype='int32')

In [29]:
print(sys.getsizeof(lista[0])*len(lista))

2800


In [30]:
print(sys.getsizeof(arr[0])*arr.size)

2800


In [36]:
import time #this library to measure time

In [42]:
x = range(100000000)
y = range(100000000,200000000)

start_time = time.time()
c = [a + b for a, b in zip(x, y)]

print(time.time()-start_time)

10.751828908920288


In [44]:
a = np.arange(100000000)
b = np.arange(100000000,200000000)

start_time = time.time()
t = a+b

print(time.time()-start_time)

0.3613293170928955
