# Slicing

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2 = np.arange(1,25)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [6]:
arr2 = arr2.reshape(2,12)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [7]:
arr2 = arr2.reshape(6,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [8]:
arr2[2]

array([ 9, 10, 11, 12])

In [11]:
arr2[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [13]:
arr2[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [14]:
for i in arr2:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]


In [15]:
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


# Operations

In [16]:
arr3 = np.arange(1,6)
arr4 = np.arange(6,11)

In [18]:
arr3

array([1, 2, 3, 4, 5])

In [19]:
arr4

array([ 6,  7,  8,  9, 10])

In [20]:
arr3+arr4

array([ 7,  9, 11, 13, 15])

In [21]:
arr3-arr4

array([-5, -5, -5, -5, -5])

In [22]:
arr3*arr4

array([ 6, 14, 24, 36, 50])

In [23]:
arr3+2

array([3, 4, 5, 6, 7])

In [24]:
arr3<3

array([ True,  True, False, False, False])

In [25]:
arr4.max()

np.int64(10)

In [26]:
arr4.min()

np.int64(6)

In [32]:
arr4.sum().item()

40

In [33]:
arr4.mean()

np.float64(8.0)

In [34]:
np.median(arr4)

np.float64(8.0)

In [36]:
arr4.std()

np.float64(1.4142135623730951)

In [37]:
np.sin(arr4)

array([-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [38]:
np.exp(arr4)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [39]:
np.sqrt(arr4)

array([2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])